# Generated by Django 5.2.4 on 2025-07-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta_restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
