# Generated by Django 5.2.4 on 2025-07-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta_restaurantes', '0002_categoria_imagen_alter_comida_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número aparece primero)'),
        ),
    ]
