# Generated by Django 5.2.4 on 2025-07-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta_restaurantes', '0003_alter_categoria_options_categoria_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
