# Generated by Django 5.2.4 on 2026-02-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta_restaurantes', '0005_subcategoria_comida_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
